### ISSUE TITLE
What about create an Enum type?

### ISSUE THREAD

**Issue by maclovin** [mtmr0x/nucleo#35]
I've been thinking about create some immutable entries in some contract fields, what you guys think about create an Enum type that can be used by the contracts?

**Comment by mtmr0x** [comment]
It looks awesome! Is there something in your mind on how it could be done for creating the contract for Enum in the best possible way?

**Comment by maclovin** [comment]
I've been thinking about create a **Predicated Type** instead a Enum, make more sense. Actually, if we think about, any contract can be a Enum object that can be used anywhere.  So, the design concept of an **Predicated Type** is something like this:

`
import {
    NucleoObject,
    NucleoString,
    NucleoPredicated
};

const UserContract = new NucleoObject({
    name: NucleoString,
    type: new NucleoPredicated(NucleoString, ['NEW', 'EXISTENT']),
});
`

**Comment by mtmr0x** [comment]
Getting back to you here since a while, sorry. 

I was evaluating a practical application for this and couldn't find how it would bring some value, since this kind of functionality looks much more as a `const` definition or, for any kind of strict value verification, you can use the `NucleoStringAssertion` or `NucleoNumberAssertion`.

If you think I'm not getting what you're talking about, I would ask if you could bring a real world implementation for this so I can see what you're seeing.

cheers
